### ISSUE TITLE
Questions about the diplomacy environment

### ISSUE THREAD

**Issue by rainwangphy** [deepmind/diplomacy#2]
Dear Authors, 

I download the code. But I cannot find where the start the diplomacy environment and how to load the released parameters for testing the agent. It seems that the environment is not correctly implemented, as with many pass options. So could you please upload the full implementation or present an example of running the game?

**Comment by atacchet** [comment]
Hello,

Thank you for your interest in our codebase and in our research. This repo does not contain implementations of a Diplomacy environment nor of a Diplomacy adjudicator.

The user needs to pair our agent with a Diplomacy environment and adjudicator to reproduce our results. The `environment/diplomacy_state.py` protocol illustrates the API expected by the agent and the tests provided ensure that the environment and agent are working as expected.

We can suggest the following OSS engines which are specifically built for research:
https://github.com/facebookresearch/diplomacy_cicero/tree/main/dipcc
https://github.com/diplomacy/diplomacy

The former is likely the best open-sourced diplomacy engine out there.
